### ISSUE TITLE
Asking to reuse your portfolio

### ISSUE THREAD

**Issue by cdhiraj40** [GregSithole/gregsithole-react-portfolio#3]
Hey Greg!!
I am Dhiraj and I got to know about your portfolio and I have to say I totally loved the simplicity. It's super clean and looks great!
I was asking if I could use your portfolio, customize and create it for myself. 
I would fork the repo and definitely give you credits!
I was also wondering how did you create the profile picture for the website [this](https://gregsithole.com/static/media/avatar-1.09f66d2157a4760a7fb5d009f6ce19dd.svg) and [this one](https://gregsithole.com/static/media/avatar-2.34202b5e28f05c3b37d92b2f73632aa4.svg).

Anyways, let me know if I could use it or not! Thanks :D

**Comment by GregSithole** [comment]
Hey 

Sure you can definitely use. 
Though the profile is based on a tutorial that I was following with a few of my own customizations here and there.

You can check the tutorial here: https://youtu.be/o3IP5HeFRO0

And in terms of the avatars I used this: https://getavataaars.com/
